### PR TITLE
Directly skip to the donation screen if the welcome message is blank

### PR DESCRIPTION
**Pull request by bumi**
If the welcomemessage is not set we can directly skip to the donation screen

@reznord can the initialization of props/state be unified? we now have code in the constructor, the componentDidMount and the setDefaults functions.

### CODE REVIEW

**Comment by reznord** [comment]
I think we can skip the `componentDidMount` part, but just left it as a fallback

**Comment by reznord** [comment]
the `setDefaults()` needs to be there since we are calling that when we close the modal.

**Review by reznord — APPROVED** [review]

**Comment by bumi** [comment]
but can we somehow call always the same function? 
e.g. call setDefaults() in the constructor and do everything in the setDefaults function?

**Comment by reznord** [comment]
normally in. constructor we initialise the state, and outside the constructor we have to update the state without mutating by using `this.setState`. If we do something like `this.foo = bar` instead of `this.setState({foo: bar})` it will mutate the state and then the whole diffing in react will be broken and it will trigger a force update all across the DOM.

**Comment by bumi** [comment]
I just feel like this is quite some duplicated code and we have no clear function where we set the initial state. (which we need when initializing but also when closing the modal)

**Pull request merged**
