### PR TITLE
Shorter state access

### PR DESCRIPTION
**Pull request by bumi**
can't we access the entries on the state object here? this makes the code a bit shorter

### CODE REVIEW

**Comment by reznord** [comment]
What is the main point of this PR? I don't see how removing the destructuring reduces the size of the bundle.

**Comment by bumi** [comment]
only the code is 12 lines shorter :)

**Comment by reznord** [comment]
destructuing doesn't add more lines of code to the bundle. Babel transpiles it the same way.

**Comment by bumi** [comment]
I am talking about that file here. it makes it longer for me as a developer to read and I first need to figure out where that variable is defined. 
`this.state.paymentOptions` is very explicit and also not much longer.

**Pull request merged**
